"""descripcion de la migracion1

Revision ID: 2b34b572d3c4
Revises: 69c7487d9a75
Create Date: 2025-10-17 14:18:37.096313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b34b572d3c4'
down_revision: Union[str, None] = '69c7487d9a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
